export * as trendings from './rest/trendings'
export * as readme from './rest/readme'
export * as starred from './rest/starred'
export * as getIssues from './rest/getIssues'
export * as authUser from './rest/authUser'
export * as followings from './rest/followings'
export * as userRepos from './rest/userRepos'